mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),
] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import re_path
from products import views

urlpatterns = [
    re_path(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True,
                                 default=None, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True,
                                default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    # print('session_key =', request.session.session_key)

    return render(request, 'products/product.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div>
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Доставка
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
                                Отзывы
                            </a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane fade in active" id="description">
                            <p>{{ product.description }}</p>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="delivery">
                            <p>У нас доставка очень быстрая! Попробуйте и убедитесь сами!</p>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="messages">
                            <p>К сожалению, отзывов об этом товаре пока нет.</p>
                        </div>
                    </div>
                </div>

                <div>
                    <form id="form_buying_product" class="form-inline" action="">
                        {% csrf_token %}
                        <div class="form-group">
                             <input type="number" min="0" class="form-control" name="number" id="number" value="1">
                        </div>
                        <div class="form-group">
                            <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id = "{{ product.id }}"
                                    data-name = "{{ product.name }}"
                                    data-price = "{{ product.price }}"
                            >
                                Добавить в корзину
                            </button>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/products/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
            <a href="{% url 'product' product_image.product.id %}">
                <img src="{{ product_image.image.url }}" class="img-responsive product-img">
            </a>
        </div>

        {% if product_image.product.discount %}
            <div class="discount-container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}

        <h4>{{ product_image.product.name }}</h4>
        <p>
            {{ product_image.product.description|truncatechars_html:75 }}
        </p>
        <div class="price">
            {{ product_image.product.price }}
        </div>
        <div class="add-to-card-btn">
            <a href="{% url 'product' product_image.product.id %}">
                <button class="btn btn-success">
                    Подробнее
                </button>
            </a>
        </div>
    </div>
</div>